function throwError() {
    throw new Error('Something unexpected happened...');
}

throwError();
